### ISSUE TITLE
[BUG/ISSUE] Rumble in native mode weaker than Xbox/Dualshock emulation 

### ISSUE THREAD

**Issue by popthemoff** [Paliverse/DSX#42]
**Describe the bug**
Maybe not a bug but in native mode game rumble is weaker compared to Xbox emulation 

**To Reproduce**
1. Switch between native and Xbox emulation 
2. See the difference in intensity?
3.

**Comment by Paliverse** [comment]
With a virtual Xbox, there’s a direct contact with the game and the data passed to the virtual controller like rumble which can be applied correctly.

In native mode, since DSX is also sending data to the physical controller, DSX is sending values of 0 for rumble which may make the rumble being sent from the game be weaker.

Only other thing that can be added is the choice of fully stopping DSX from sending data to the virtual controller which I will probably add once I get the time. Just remind me if I forget.
